config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations" }

  resources :users, only: [:profile] do
    member do
      get "profile"
    end
  end

  scope "/admin" do
    resources :users
  end
  root 'welcome#index'
  resources :welcome do
    collection do
      get 'about'
      get 'advise'
    end
  end
  resources :patterns do
    collection do
      post 'uploadfile'
      get 'getfilename'
      post 'uploadrectarray'
      post 'getediturl'
      post 'getrectarray'
      get 'getrectarray'
      get 'getediturl', action: :get_edit
    end
  end
  resources :messages
  resources :colors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/pattern.rb
class Pattern < ApplicationRecord
  has_many :pattern_colors

  def self.search(search)
    scope = all
    if search
      scope.where(row_number: search)
    else
      scope
    end
  end
end

app/controllers/patterns_controller.rb
class PatternsController < ApplicationController
  before_action :load_pattern, only: [:getrectarray, :getediturl, :getfilename]
  before_action :new_pattern, only: [:uploadfile, :uploadrectarray]
  skip_before_action :verify_authenticity_token

  def index
    @patterns = Pattern.all
    respond_to do |format|
      format.html
      format.json { render json: @patterns }
    end
  end

  def uploadfile
    uploaded_io = params[:file]
    @file = params[:file]
    File.open(Rails.root.join('public', 'uploads', "#{uploaded_io.original_filename}_#{rand(1..10000)}"), 'wb') do |file|
      file.write(uploaded_io.read)
    end
  end

  def getfilename
    respond_to do |format|
      format.json { render json: @last_pattern }
    end
  end

  def uploadrectarray
    @upload_pattern.row_number = params[:array][:row_number]
    @upload_pattern.col_number = params[:array][:col_number]
    @upload_pattern.pattern_img = params[:array].to_json.to_s
    @upload_pattern.save

    respond_to do |format|
      if @upload_pattern.save
        format.html { redirect_to @upload_pattern }
        format.json { redirect_to @upload_pattern }
      else
        format.html { render :new }
        format.json { render json: @upload_pattern.errors, status: :unprocessable_entity }
      end
    end
  end

  def getrectarray
    respond_to do |format|
      format.html
      format.json { render json: @last_pattern }
    end
  end

  def getediturl
    puts @last_pattern
  end

  def get_edit
  end

  def create
    @pattern = Pattern.new

    respond_to do |format|
      if @pattern.save
        format.html { redirect_to @pattern, notice: 'Task was successfully created.' }
        format.json { redirect_to @pattern }
      else
        format.html { render :new }
        format.json { render json: @pattern.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def new_pattern
    @upload_pattern = Pattern.new
  end

  def load_pattern
    @last_pattern = Pattern.last
  end

  def secure_params
    params.require(:pattern).permit(:name, :description, :row_number, :col_number, :user_id, :pattern_img)
  end
end

app/views/patterns/_index.html.erb
<div class="tab_container">
  <h2>Jauns Raports</h2>
  <div>
    <div class="form-group row">
      <label for="example-text-input" class="col-2 col-form-label">Rindas</label>
      <div class="col-10">
        <input class="form-control row-boxes" type="text">
      </div>
    </div>
    <div class="form-group row">
      <label for="example-text-input" class="col-2 col-form-label">Kolonnas</label>
      <div class="col-10">
        <input class="form-control column-boxes" type="text">
      </div>
    </div>
    <button class="btn btn-primary" type="button" id="new-pattern">Jauns Raports</button>
  </div>
  <h2>Jauns Raports No Attēla</h2>
  <div class="panel panel-default">
    <div class="panel-body">

      <!-- Standar Form -->
      <h4>Izvēlies bildi no datora</h4>
      <form action="" method="post" enctype="multipart/form-data" id="js-upload-form">
        <div class="form-inline">
          <div class="form-group">
            <input type="file" name="files[]" id="js-upload-files">
          </div>
          <button type="submit" class="btn btn-sm btn-primary" id="js-upload-submit">Augšupielādet bildi</button>
        </div>
      </form>

      <!-- Drop Zone -->
      <h4>Vai ievelciet bildi šeit</h4>
      <div class="upload-drop-zone" id="drop-zone">
        Ievelc bildi šeit
      </div>
      
    </div>
  </div>
</div>

app/views/patterns/get_edit.html.erb
<html>
  <head>
    <title>Pattern</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons"/>
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css"/>
    <script defer="" src="https://code.getmdl.io/1.3.0/material.min.js"></script>
    <style>
      /* svg css */
      /* Grid line color */
      .axis line {fill: none;stroke: #d00;shape-rendering: crispEdges;vector-effect: non-scaling-stroke;}
      /* make the Element stretch to fill the screen in WebKit */
      :-webkit-full-screen svg {width: 100%;height: 100%;}
      #pattern { z-index: 1;}
      #toolset {
          position: absolute;
          z-index: 3;
          top: 0;
          height: 100vh;
          width: 300px;
          background-color: #efefef;
          box-shadow: 0 0 0 0 #3f3f3f;
          right: 0;
        /*  transform: translateX(-400px);
          transition: transform 0.5s ease-in-out; */
      }
      .base {
          display: 'none'
      }
      .objects {
          display: 'pattern'
      }
      svg { z-index: 2;}
    </style>
  </head>
</html>
<body>
  <div id="bg1"></div>
  <main class="mdl-layout mdl-js-layout">
    
    <div id="dialog">
      <dialog id="colPick" class="mdl-dialog">
        <p class="mdl-dialog__title">Color picker</p>
        <div class="mdl-dialog__actions"></div>
        <button type="button" id="colPickClose" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent">Close</button>
      </dialog>
    </div>
    <div class="mdl-layout__content">
      <div id="toolset">
        <form>
          <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
            <label for="column-boxes" class="mdl-textfield__label">Active Layer:</label>
            <input name="column-boxes" type="text" value="Base layer" class="mdl-textfield__input column-boxes"/><span class="mdl-textfield__error">Something...!</span>
          </div>
          <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
            <label for="row-boxes" class="mdl-textfield__label">Name/ID:</label>
            <input type="text" value="" id="filename" class="mdl-textfield__input row-boxes"/><span class="mdl-textfield__error">Something ....!</span>
          </div>
          <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
            <select id="propertyType" form="addProperty" name="propertyType" class="select form-control input-lg">
              <option value="1">Base</option>
              <option value="3">Pattern</option>
              <!--option(value='6') Pedestrian-->
              <!--option(value='7') Car-->
              <!--option(value='10') Signs-->
              <!--option(value='11') Traffic Lights-->
              <!-- sample layers - not defined by any means-->
            </select>
          </div>
          <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
            <button type="button" id="color-btn" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent">Color Picker</button>
          </div>
          <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
            <div id="activeColor">
              <h4>Brush color</h4>
            </div>
          </div>
          <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
            <button type="button" id="saveEditedImage" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent">Save Pattern</button>
          </div>
        </form>
      </div>
      <div id="pattern"></div>
    </div>
  </main>
  <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  <script src="https://d3js.org/d3.v3.js"></script>
</body>

app/views/patterns/index.html.erb
<div class="jumbotron">
  <h1>Raportu meklēšana</h1>
  <%= form_tag patterns_path, :method => 'get' do %>
    <div class="form-group row">
      <label class="col-2 col-form-label">Valdziņu skaits</label>
      <div class="col-10">
        <%= select_tag "Valdziņu skaits", options_for_select((1..50)), class: 'form-control select_input', id: 'row_input' %>
      </div>
    </div>
    <div class="form-group row">
      <label class="col-2 col-form-label">Krāsu skaits</label>
      <div class="col-10">
        <%= select_tag "Krāsu skaits", options_for_select((1..10)), class: 'form-control select_input', id: 'row_input' %>
      </div>
    </div>
    <div class="actions">
      <%= submit_tag "Meklēt", :name => nil, class: 'btn btn-primary' %>
      <a href="/">Atpakaļ</a>
    </div>
  <% end %>
</div>
<div class="jumbotron">
  <h1>Raporti</h1>
</div>